BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SUBSTATIONS" (
	"id"	INTEGER NOT NULL UNIQUE,
	"maintance_id"	INTEGER CHECK("maintance_id" <> ''),
	"name"	TEXT NOT NULL CHECK("name" <> ''),
	"voltage_level"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("maintance_id") REFERENCES "MAINTANCE"("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "MAINTANCE" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL UNIQUE,
	"short_name"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "SUBSTATIONS" VALUES (1,1,'Kostanaiskaya','10/35/10');
INSERT INTO "SUBSTATIONS" VALUES (2,1,'Gorodskaya','110/10');
INSERT INTO "SUBSTATIONS" VALUES (3,1,'Leninskaya','220/110/35/10');
INSERT INTO "MAINTANCE" VALUES (1,'ТОО "Межрегионэнерготранзит"','МРЭТ');
INSERT INTO "MAINTANCE" VALUES (2,'ТОО "KamLitKZ"','KamLit');
INSERT INTO "MAINTANCE" VALUES (3,'ТОО "СпектрЭнергоСервис"','СпектрЭС');
COMMIT;
